name: Parallel Execution Different Browser
on: push
jobs:
  registration-Chrome:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:registration -- --browser chrome
      - name: Cypress Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Mochaawsome Reports - registration
          path: cypress/reports/html

  search-Edge:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:addToCart -- --browser edge
      - name: Cypress Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Mochaawsome Reports AddToCart
          path: cypress/reports/html
